### ISSUE TITLE
soma size

### ISSUE THREAD

**Issue by SabriQ** [schlegelp/navis#16]
I try to show somata in lager size, while I see the code in which "soma" is a boolean variable. 
in your opinion, how should I change the soma size?
Thanks.

**Comment by schlegelp** [comment]
A bit of context/example code would be useful. I'm guessing this is for `plot3d` and `TreeNeuron`? If so, the size of the sphere representing the soma is determined by the `radius` column in the node table. So increasing that value should also increase the size of the soma for plotting.

**Comment by schlegelp** [comment]
Actually looking at the code, you can set a `soma_radius` which by default looks for the `"radius"` columns for `TreeNeurons`. But you can set it to an arbitrary value. So for example:
```Python
# Load some example neuron
nl = navis.example_neurons(2)
# Set the soma radius to an arbitrary value for plotting
nl[0].soma_radius = 500
nl[1].soma_radius = 2000
# Plot with the new radii
nl.plot3d()
```
Should probably document that better.

**Comment by SabriQ** [comment]
Thanks a lot.  `soma_radius` does work.
