### ISSUE TITLE
Unable to load swc file from simple neurite tracer

### ISSUE THREAD

**Issue by SridharJagannathan** [schlegelp/navis#21]
Hi @schlegelp ,
I recently tried to trace a gal4 line in the simple neurite tracer in FiJi and tried to load the trace (`.swc`) into `navis` however, I'm running into the below error. I was able to load the same `.swc` file in `natverse`. The error is as follows ( I have also attached the file here [VFB_00023647_snt_skel-000.swc.zip](https://github.com/schlegelp/navis/files/6026345/VFB_00023647_snt_skel-000.swc.zip))
```
swc_files = '/Users/sri/Documents/Python/gal4_flywire/VFB_00023647_snt_skel-000.swc'
vfb_neuron = navis.read_swc(swc_files)
```

resulting in..
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-7-d0edd8d77f78> in <module>
----> 1 vfb_neuron = navis.read_swc(swc_files)

~/opt/anaconda3/lib/python3.8/site-packages/navis/io/swc_io.py in read_swc(f, connector_labels, soma_label, include_subdirs, delimiter, parallel, precision, **kwargs)
    192                                 skiprows=len(header),
    193                                 header=None)
--> 194             nodes.columns = ['node_id', 'label', 'x', 'y', 'z',
    195                              'radius', 'parent_id']
    196         except BaseException:

~/opt/anaconda3/lib/python3.8/site-packages/pandas/core/generic.py in __setattr__(self, name, value)
   5150         try:
   5151             object.__getattribute__(self, name)
-> 5152             return object.__setattr__(self, name, value)
   5153         except AttributeError:
   5154             pass

pandas/_libs/properties.pyx in pandas._libs.properties.AxisProperty.__set__()

~/opt/anaconda3/lib/python3.8/site-packages/pandas/core/generic.py in _set_axis(self, axis, labels)
    562     def _set_axis(self, axis: int, labels: Index) -> None:
    563         labels = ensure_index(labels)
--> 564         self._mgr.set_axis(axis, labels)
    565         self._clear_item_cache()
    566 

~/opt/anaconda3/lib/python3.8/site-packages/pandas/core/internals/managers.py in set_axis(self, axis, new_labels)
    224 
    225         if new_len != old_len:
--> 226             raise ValueError(
    227                 f"Length mismatch: Expected axis has {old_len} elements, new "
    228                 f"values have {new_len} elements"

ValueError: Length mismatch: Expected axis has 4 elements, new values have 7 elements
```

**Comment by schlegelp** [comment]
It looks like the file is a mix of tab and space separators. See this:
```Python
>>> # With default separator
>>> pd.read_csv('VFB_00023647_snt_skel-000.swc', header=None, skiprows=6)
                                                      0
0     1\t0\t231.908032 219.526534 88.631724 0.000000...
1     2\t0\t232.426842 219.007559 88.631724 0.000000\t1
2     3\t0\t232.945652 219.007559 88.631724 0.000000\t2
3     4\t0\t233.464462 219.007559 88.631724 0.000000\t3
4     5\t0\t233.983271 219.007559 88.631724 0.000000\t4
>>> # With tab separator
>>> pd.read_csv('VFB_00023647_snt_skel-000.swc', header=None, skiprows=6, sep='\t')
         0  1                                         2     3
0        1  0  231.908032 219.526534 88.631724 0.000000    -1
1        2  0  232.426842 219.007559 88.631724 0.000000     1
2        3  0  232.945652 219.007559 88.631724 0.000000     2
3        4  0  233.464462 219.007559 88.631724 0.000000     3
4        5  0  233.983271 219.007559 88.631724 0.000000     4
```
Bottom line: that's an issue with pandas (or the underlying Python csv parser) not being able to disentangle the mix of separators. Is there a way to change the output of the simple neurite tracer? Alternatively, you could write a little script to clean up the file(s). `navis.read_swc` has a `delimiter` parameter which defaults to `' '` whitespace and is passed directly to `pandas.read_csc`.

**Comment by schlegelp** [comment]
Ah: a workaround is using a regex separator.
```Python
pd.read_csv('VFB_00023647_snt_skel-000.swc', header=None, skiprows=6, sep='[\t ]')
```

**Comment by schlegelp** [comment]
By-the-by: it struck me that the neuron has one one root and one end node - no branch points. Did you realize that this is one continuous line? I.e. when a neurite ends the skeleton just turns around, forms a loop and tracks back.

**Comment by SridharJagannathan** [comment]
Thanks, I just realised that the file seems to have arbitary number of spaces as delims and your solution to set the seperator as `\s+`, seems to have done the trick.
The neuron (tracing) actually looks fine when i plot it see below:
![gal4line](https://user-images.githubusercontent.com/13106358/108834073-9db7af00-75c5-11eb-9a5b-b5f529d3a932.png)

Perhaps I need to reroot it, somehow?
I was just trying to do some covisualisation of `gal4line`, `hemibrain`, `flywire` neuron ( `ilPN`) as an example here: 
https://github.com/SridharJagannathan/pyroglancer/blob/master/pyroglancer/examples/gal4line2flywire.ipynb

**Comment by schlegelp** [comment]
It will plot just fine but anything that requires correct topology will fail.

**Comment by SridharJagannathan** [comment]
I tried to cut the neuron and then stitch them back together, that seems to have produced branches, however i can see that there are loops inside the neuron, do you know how to eliminate them, basically i'm thinking of an approach to use the pts to construct a graph, and then use the graph to construct the neuron.
```
vfb_neuron = navis.read_swc(swc_files, delimiter='\s+')
fragments = navis.cut_neuron(vfb_neuron, 500)
stitched = navis.stitch_neurons(fragments, method='ALL')
```

**Comment by schlegelp** [comment]
With 84cfe9f19e28c349a0f215af6e2ab7b2ba63a17c I just pushed a first pass implementation for a function that resolves this (albeit not perfectly):
```Python
>>> n = navis.read_swc('VFB_00023647_snt_skel-000.swc', delimiter='\s+')
>>> fx = navis.graph.clinic.merge_duplicate_nodes(n)
>>> fx
type                     navis.TreeNeuron
name            VFB_00023647_snt_skel-000
n_nodes                              1422
n_connectors                         None
n_branches                             59
n_leafs                                61
cable_length                  1106.133057
soma                                 None
units                        1 micrometer
```
You can see it now has proper leafs and branches. However when co-visualizing it, you will notice that some edges got removed (red) to break up cycles after node collapse. It's better than before but not perfect.

<img width="406" alt="Screenshot 2021-02-23 at 12 56 14" src="https://user-images.githubusercontent.com/7161148/108846821-e6c42f00-75d6-11eb-95c3-a5db45916c44.png">

**Comment by schlegelp** [comment]
I'll close this issue. Re-open if you feel this is unresolved.
