### ISSUE TITLE
Transformation graphs

### ISSUE THREAD

**Issue by clbarnes** [schlegelp/navis#27]
This might be a use case already covered by something else, or might be a stupid idea, but I can envision a situation where you have different transformations for different types of task; e.g. between brains, between sides, and between segments. In this case, rather than generating a `Transform` for every permutation, it might be handy to create a `TransformSequence` on the fly which e.g. transforms a neuron from its current segment into a better-reconstructed segment, then flips it to the other side, then registers it in a different brain.

This could be done with a `TransformGraph` class, which would wrap a `networkx.OrderedDiGraph`. You populate the graph in some arbitrary nodes each representing a space, and then add edges which each have a `Transform` object for when you know how to transform between those spaces. Reverse edges could be populated with inverse transforms if they are not given explicitly. Then when you need to transform some points from space A to space B, the graph is traversed and a `TransformSequence` is created based on the path.

You could easily add weights to this graph if there were some transformations you had more faith in than others.

You could make it more robust by looking for multiple paths and finding a consensus deformation by weighting the results of each path by the length of the path, but of course this would be slower.

**Comment by schlegelp** [comment]
If I understand you correctly then this this functionality already exists. A couple notes:

1. `navis.transforms.registry.find_bridging_path(source, target)` (an instance of `navis.transforms.templates.TemplateRegistry`) uses a graph to collect on-the-fly all required transforms to go from a given source to a given target even if that involves more than a single transform into a `TransformSequence`. This also works with inverse directions. 
2. The above takes weights into account which can be used to prioritise "good" over "bad" transforms (although I'm not making use of that at the moment).
3. As you pointed out in certain cases it might be beneficial to perform a certain operation in a specific brain space. Mirror is the first thing that comes to mind and indeed, `navis.mirror_brain` already has a `via` parameter that when set will transform the data to space X, perform the mirroring and then transform back to the original space. 
4. Currently, `navis` only knows two types of transforms: "bridging" to go from one space to the other, and "mirror" to offset left/right asymmetries. We could add more types but so far I have resorted to just making up new templates spaces as required. For example to move between larval T1 and T2 segments, I would register a transform between "T1" and "T2" and then use `navis.xform(some_data, source='T1', target='T2')`.

Does that already cover what you had in mind? I'd be happy to extend the system as required (as long as it remains reasonably simple).

**Comment by schlegelp** [comment]
Just to note that I copied that design pretty much 1:1 from Greg's `nat`.

**Comment by clbarnes** [comment]
Yes, that's it! Sorry I didn't find it :s

**Comment by schlegelp** [comment]
Good idea though! :)
