### ISSUE TITLE
BrokenPipeError when calling xform_brain

### ISSUE THREAD

**Issue by ariematsliah-princeton** [schlegelp/navis#32]
Greetings, can you please help with this issue?

navis version: 0.5.2

Repro:
```
import flybrains
import fafbseg
import navis

flybrains.download_jefferislab_transforms()
flybrains.download_saalfeldlab_transforms()
flybrains.register_transforms()

navis.transforms.registry.summary()

sk = navis.read_swc("new_dp.swc")
tsk = navis.xform_brain(x=sk, source="JFRC2", target="FAFB14")

[new_dp.swc.zip](https://github.com/schlegelp/navis/files/6321936/new_dp.swc.zip)

```

Error:

```
 File "/root/miniconda3/envs/flywire-transforms/lib/python3.8/site-packages/navis/transforms/templates.py", line 770, in xform_brain
    return xform(x, transform=trans_seq, caching=caching,
  File "/root/miniconda3/envs/flywire-transforms/lib/python3.8/site-packages/navis/transforms/xfm_funcs.py", line 135, in xform
    xyz_xf = xform(xyz,
  File "/root/miniconda3/envs/flywire-transforms/lib/python3.8/site-packages/navis/transforms/xfm_funcs.py", line 196, in xform
    return transform.xform(x, affine_fallback=affine_fallback)
  File "/root/miniconda3/envs/flywire-transforms/lib/python3.8/site-packages/navis/transforms/base.py", line 176, in xform
    xf[~is_nan] = tr.xform(xf[~is_nan],
  File "/root/miniconda3/envs/flywire-transforms/lib/python3.8/site-packages/navis/transforms/cmtk.py", line 412, in xform
    proc.stdin.write(points_str.encode())
BrokenPipeError: [Errno 32] Broken pipe
```

**Comment by ariematsliah-princeton** [comment]
[new_dp.swc.zip](https://github.com/schlegelp/navis/files/6321940/new_dp.swc.zip)

**Comment by schlegelp** [comment]
That repex works for me which will make debugging things a bit harder. But it apparently is an issue with the CMTK transform from `JFRC2` to `FCWB`.

Am I correct in that you are on OSX (which version?) and using Python 3.8?

Could you please:

1. Check your CMTK version by running this in a terminal:
```bash
$ streamxform --version
3.3.1
```

2. Try transforming the first point in your neuron manually in the terminal:
```bash 
$ streamxform -- --inverse /Users/philipps/flybrain-data/JFRC2_FCWB.list <<< "304.835266 67.587410 20.948561"
337.317581 78.3538961 20.3971305
```

In above code you will need to change the directory where your `JFRC2_FCWB.list` lives. It should be in `/Users/YOURUSER/flybrain-data` but you can also look it up like so:

```Python
>>> navis.transforms.registry.find_bridging_path('JFRC2', 'FAFB14')[1][0].regs
```

**Comment by schlegelp** [comment]
Also on a side note:

It looks like your `new_dp.swc` is actually a dotprop - i.e. points + vectors - that was saved as SWC skeleton. I hadn't considered that this something people might do but I see now that that's a reasonable way to save/load dotprops.

`navis.read_swc` always loads SWC as skeletons (i.e. `navis.TreeNeuron`) which works just fine for visualisation but you will run into problems for any function that expect a properly connected skeleton. Also: if you wanted to use your `new_dp` for NBLASTing, you would need to turn it from `navis.TreeNeuron` into a `navis.Dotprop` which feels redundant and would in the naive approach actually change the dotprop in the process. 

If working with SWC-encoded dotprops is relevant for your work, I was wondering if it would be useful to have the option to read SWC into `navis.Dotprops` (perhaps even automatically detecting whether the file is a dotprop or a skeleton)? Likewise, `navis` does not currently let you save Dotprops to SWCs directly but that could be implemented.

**Comment by ariematsliah-princeton** [comment]
Hi @schlegelp - thank you for the quick and detailed response.
I am developing on OSX but the code is running on Linux
```
streamxform --version
streamxform: command not found
```

Maybe I didn't install CMTK correctly? I do see this:
```
ls /usr/bin/cmtk 
/usr/bin/cmtk
```

Regarding your second response - I'm new to this world (joined Murthy lab at Princeton as research engineer recently) and probably missing some basic understanding of various formats. `new_dp.swc` was indeed generated from dotprop (using the `.to_skeleton()` method).

As for what I'm trying to do here - in a nutshell it's a web service that translates neuron skeletons from any template using Navis and maps them to FlyWire. Would love to give you a quick overview if you're available. My email is arie@princeton.edu

Thanks

**Comment by schlegelp** [comment]
Just to clarify: there is a `/usr/bin/cmtk/streamxform`? If so, can you run this:
```bash
$ /usr/bin/cmtk/streamxform --version
```

Also please check where navis thinks `streamxform` is (see point 3 above).

I also seem to remember that @sdorkenw had a similar problem. Not sure if that ever got solve or just ignored because we figured he didn't actually need CMTK.

**Comment by ariematsliah-princeton** [comment]
Nope I have no `/usr/bin/cmtk/streamxform`

`/usr/bin/cmtk` is just a script - I probably didn't install it from the right place? I downloaded the package here:
https://www.nitrc.org/frs/download.php/8200/CMTK-3.3.1-Linux-x86_64-core.rpm

**Comment by ariematsliah-princeton** [comment]
Re: Also please check where navis thinks streamxform
Navis is not able to find streamxform

**Comment by schlegelp** [comment]
I don't think I ever installed CMTK for Linux myself (or it's been so long that I don't remember anymore) so no insights there. However, `streamxform` and the other CMTK binaries have to be somewhere. For example, I just checked our Linux server and there CMTK the CMTK binaries are in `/usr/local/lib/cmtk/bin/` (one of the paths navis looks for).

You could try this to find it:
```
find ~ -name streamxform
```

**Comment by schlegelp** [comment]
You could also check `~/dev/src/cmtk/build/bin/`.

**Comment by ariematsliah-princeton** [comment]
Ok making some progress :)
I reinstalled it, and verified it is now available:
```
/usr/lib/cmtk/bin/streamxform --version
3.3.1
```

Also this works:
```
navis.transforms.cmtk.find_cmtkbin()
PosixPath('/usr/local/lib/cmtk/bin')
```

However the same error persists, any hints how to continue from here?

Thank you

**Comment by schlegelp** [comment]
Hmmm is `/usr/lib/cmtk/bin/` the same as `/usr/local/lib/cmtk/bin`? I.e. does this work:

```bash 
$ /usr/local/lib/cmtk/bin/streamxform --version
```

If so, can you try this then:

```Python
>>> import subprocess
>>> subprocess.Popen(['/usr/local/lib/cmtk/bin/streamxform', '--version'])
```

**Comment by schlegelp** [comment]
Also going back to my original response, please try this (changing the path to where you have downloaded the transform to):
```bash
$ /usr/local/lib/cmtk/bin/streamxform -- --inverse /Users/philipps/flybrain-data/JFRC2_FCWB.list <<< "304.835266 67.587410 20.948561"
337.317581 78.3538961 20.3971305
```

**Comment by ariematsliah-princeton** [comment]
Lookls like not:
```
/usr/local/lib/cmtk/bin/streamxform --version
/usr/local/lib/cmtk/bin/streamxform: error while loading shared libraries: libdcmdata.so.4: cannot open shared object file: No such file or directo
ry
```
similarly:
```
>>> import subprocess
>>> subprocess.Popen(['/usr/local/lib/cmtk/bin/streamxform', '--version'])
<subprocess.Popen object at 0x7f9d25649640>
>>> /usr/local/lib/cmtk/bin/streamxform: error while loading shared libraries: libdcmdata.so.4: cannot open shared object file: No such file or dir
ectory
```

**Comment by ariematsliah-princeton** [comment]
This works:
```
/usr/lib/cmtk/bin/streamxform -- --inverse ~/flybrain-data/BridgingRegistrations/JFRC2_FCWB.list <<< "304.835266 67.587410 20.948561"
337.317581 78.3538961 20.3971305 
```

However with `/usr/local/lib/cmtk/bin/streamxform` it fails as expected.

**Comment by schlegelp** [comment]
Well that would explain the Broken Pipe error. So to me it looks like there are two versions of CMTK installed and the one in `/usr/local/lib/cmtk/bin/` is broken. You could try removing that but I don't know if that would break something else on your system.

As workaround I would recommend telling navis specifically which CMTK path to use:

```Python
>>> import navis
>>> from pathlib import Path
>>> navis.transforms.cmtk._cmtkbin  = Path('/usr/lib/cmtk/bin')
```

**Comment by ariematsliah-princeton** [comment]
Note also that for me the "*.list"s are under the BridgingRegistrations sub-folder (not sure if this is an issue).

**Comment by schlegelp** [comment]
> Note also that for me the "*.list"s are under the BridgingRegistrations sub-folder (not sure if this is an issue).

That should not be a problem.

**Comment by ariematsliah-princeton** [comment]
Looks like `navis.transforms.cmtk._cmtkbin = Path('/usr/lib/cmtk/bin')` did the job - thank you
Now I see that it is hanging for a few minutes already. How long should a transform of this size take?

**Comment by schlegelp** [comment]
Are you running your original example? That takes ~4s on my machine.

**Comment by schlegelp** [comment]
Since this is actually 4 sequential transforms (`JFRC2 -> FCWB -> JRC2018F -> FAFB14um -> FAFB14`), you could try it step by step to see where it hangs:

```Python
>>> tsk1 = navis.xform_brain(x=sk, source="JFRC2", target="FCWB")
>>> tsk2 = navis.xform_brain(x=tsk1, source="FCWB", target="JRC2018F")
>>> tsk3 = navis.xform_brain(x=tsk2, source="JRC2018F", target="FAFB14um")
>>> tsk4 = navis.xform_brain(x=tsk3, source="FAFB14um", target="FAFB14")
```

**Comment by ariematsliah-princeton** [comment]
It hangs on the first one, and able to complete FCWB-> FAFB14 in couple seconds.
Is there anything special in JFRC2->FCWB that requires GPU or some other acceleration?

**Comment by ariematsliah-princeton** [comment]
And while it hangs CPU is idle

**Comment by ariematsliah-princeton** [comment]
Single point transform does not hang:
`tsk1 = navis.xform_brain(x=[[304.835266,67.587410,20.948561]], source="JFRC2", target="FCWB", verbose=True)`

**Comment by schlegelp** [comment]
The first transform is the only CMTK transform in the whole chain. 
So

**Comment by ariematsliah-princeton** [comment]
Will investigate and reopen if need help. Thank you!

**Comment by ariematsliah-princeton** [comment]
Hi @schlegelp, are you aware of any recent change or update that might be causing transform failures? I did not see any details in logs, but call to transforms hangs in our Flywire Gateway tool that uses Navis. It started ~3-4 days ago.

Thank you

**Comment by schlegelp** [comment]
That is probably because Eric Perlman and David Bock moved the server hosting the deformation field from Janelia to Vermont. It _should_ be up again but you will need to update fafbseg from GitHub (the URLs changed). Let me know if the problem persists.
