### ISSUE TITLE
size of points in 3d plots are not scaled properly

### ISSUE THREAD

**Issue by SridharJagannathan** [schlegelp/navis#4]
To reproduce:
```
import numpy as np
import navis

pts = np.array([[18475.98789451, 28713.40566046, 31338.67255543],
                         [17709.24328012, 29031.00978332, 27768.92545872]])
navis.plot3d(pts,scatter_kws={"size": 5})
```

The size of the plotted points are not scaled, the issue is here:
https://github.com/schlegelp/navis/blob/b655256d7bac8e09bb6d1040306e0f1ce590b0f8/navis/plotting/ddd.py#L293

this line should be changed to:
```
trace_data += scatter2plotly(points, **scatter_kws)
```

**Comment by schlegelp** [comment]
Fixed with 083c5971274218eedeb3243c76d04e7eec4f0053

Thanks for the catch!
