### ISSUE TITLE
intersection_matrix returns error when running a dict with key as glom, value as navis.Volume

### ISSUE THREAD

**Issue by SridharJagannathan** [schlegelp/navis#42]
To reproduce this issue run like below.. 
```
navis.intersection_matrix(allln_skel,meshes, attr = 'cable_length')
```
Here, `allln_skel` comes from some al local neurons fetched via `neu.fetch_skeletons`
`meshes` is a dict with key as glom(or some other name) and values as navis.Volume

The problem seems to be in this line

https://github.com/schlegelp/navis/blob/cf49958669c594e686ca4c98d53e0950a1131eb5/navis/intersection/intersect.py#L249

when enumerating over a dict, the values enumerated are index and key and not key and value as assumed here.
I solved it like
```
volume = {dictkey: utils.make_volume(volume[dictkey]) for idx, dictkey in enumerate(volume)}
```

**Comment by schlegelp** [comment]
Fixed with be5f424a258110a77623a2355c2ba8744d61d36f
