### ISSUE TITLE
question about geodasic distance

### ISSUE THREAD

**Issue by zylittlep** [schlegelp/navis#48]
Hi, I'm trying to measure the geodesic distance between nodes and I noticed that some distance value was inf (I used geodesic_matrix function). And when I do dist_between the two specific nodes say node IDs are X and Y, I got the error message Node Y not reachable from X. Could you please elaborate on what it means and why some nodes are not reachable to another? Thank you very much.

**Comment by schlegelp** [comment]
For the record (and I think you may have figured this out yourself): I suspect your skeleton consists of disconnected fragments (i.e. has multiple roots). You can try fixing that using `navis.heal_fragmented_neuron`.
