### ISSUE TITLE
upload_neuron sends wrong argument to navis.write_swc()

### ISSUE THREAD

**Issue by kuanawanda** [schlegelp/navis#50]
I get an error here when trying to upload a neuron https://github.com/schlegelp/pymaid/blob/9bdd2cc5a3312e4971fff12e772b90129b298c75/pymaid/upload.py#L512
> TypeError: write_swc() got an unexpected keyword argument 'filename'

Navis.write_swc() appears to expect 'filepath' instead of 'filename'. 
https://github.com/schlegelp/navis/blob/fb706e2ba7f7776aaf204a67131396d3730027a2/navis/io/swc_io.py#L887

Changing 'filename' to 'filepath' in L512 of upload.py in pymaid seemed to fix the problem.

**Comment by schlegelp** [comment]
Good catch! Looks like that parameter changed in 2b937cbc2faf541c1ddbac78a7cbf97c06f48965 which made it into navis `0.5.3`. This is now fixed with schlegelp/pymaid@a5416e96b7c2c286dd7f1aa206a7f5f97bddaff7. I also released a new pymaid version `2.0.6` which should be on PyPI shortly.

**Comment by schlegelp** [comment]
Hi. Can this issue be closed?

**Comment by kuanawanda** [comment]
sure, thanks!
